# Generated by Django 5.1.1 on 2024-09-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModeloGreenMarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_producto',
            field=models.CharField(max_length=100),
        ),
    ]
