# Generated by Django 5.1.1 on 2024-09-30 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModeloGreenMarket', '0002_alter_producto_imagen_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
