# Generated by Django 5.1.1 on 2024-10-03 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModeloGreenMarket', '0003_rename_contraseña_proveedor_contrasena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='id_carrito',
        ),
        migrations.RemoveField(
            model_name='items',
            name='id_carrito',
        ),
        migrations.RemoveField(
            model_name='items',
            name='id_producto',
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pagado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModeloGreenMarket.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
