# Generated by Django 5.1.1 on 2024-10-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModeloGreenMarket', '0003_rename_contraseña_proveedor_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='imagen_proveedor',
            field=models.ImageField(blank=True, null=True, upload_to='proveedores/'),
        ),
    ]
