# Generated by Django 5.1.1 on 2024-10-04 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModeloGreenMarket', '0004_remove_venta_id_carrito_remove_items_id_carrito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='creado_en',
        ),
    ]
